app:
   name: Student Info App From Properties
   version: 1.0.9
   security:
     signing-key: aaa
     encoding-strength: 256
     security-realm: Spring Boot JWT Example Realm
     jwt:
       resource-id: studentapi
       client-id: Mahammad
       client-secret: Mahammad
       grant-type: password
       scope-read: read
       scope-write: write

spring:
   datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     url : jdbc:mysql://localhost/spring-boot?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
     username: root
     password: 12345